version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - echo Installing requirements...

  build:
    commands:
      - echo Running tests...
      - pytest test.py --maxfail=1 --disable-warnings --tb=short

artifacts:
  files:
    - '**/*'