name: CI/CD to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t flask-app:${{ env.IMAGE_TAG }} .

      - name: Load image into Minikube
        run: |
          minikube image load flask-app:${{ env.IMAGE_TAG }}

      - name: Clone manifests repo
        run: |
          git clone https://x-access-token:${{ secrets.GIT_KEY }}@github.com/Jonathan1503/k8s-cicd

      - name: Update image tag
        run: |
            cd k8s-cicd
            sed -i "s|image: flask-app:.*|image: flask-app:${{ env.IMAGE_TAG }}|" deployment.yaml
            
      - name: Commit and push to manifests repo
        run: |
          cd k8s-cicd
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push



      
