name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
          --platform linux/amd64 \
          -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ env.IMAGE_TAG }} \
          --push .

      - name: Run Unit Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ env.IMAGE_TAG }} pytest test.py --maxfail=1 --disable-warnings --tb=short


      - name: Clone manifests repo
        run: |
          git clone https://x-access-token:${{ secrets.GIT_KEY }}@github.com/Jonathan1503/k8s-cicd

      - name: Update image tag in Kubernetes manifests
        run: |
          cd k8s-cicd
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ env.IMAGE_TAG }}|" deployment.yaml

      - name: Commit and push updated manifests
        run: |
          cd k8s-cicd
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
