name: CI/CD to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .

      - name: Load image into Minikube
        run: |
          minikube image load flask-app:latest

      
